project:
  type: book
  pre-render: R/setup.R

callout-appearance: simple
# see this quarto discussion issue for info on lua filter
# https://github.com/quarto-dev/quarto-cli/discussions/2869#discussioncomment-3886253
filters: 
 - chapters/lua/callouts.lua

execute:
  freeze: auto  
  echo: true 
  dev: "ragg_png"
  dpi: 740 
  out.width: "80%"
  fig.width: 6
  fig.asp: 0.618
  fig.retina: 3
  fig.align: "center"
  fig.show: "hold"

book:
  title: "Causal Inference in R 中文版"
  author: ["Malcolm Barrett, et al.", "陆震（译）"]
  date: "today"
  repo-url: https://github.com/Leslie-Lu/Causal-Inference-in-R-Chinese
  repo-actions: [edit, issue]
  chapters:
    - index.qmd

    - chapters/99-references.qmd

bibliography: citations.bib

format:
  html:
    code-link: true
    tbl-cap-location: bottom
    theme:
      - cosmo
      - style.scss
    include-in-header: "plausible.html"
    email-obfuscation: javascript
  # pdf:
  #   documentclass: scrreprt

email-obfuscation: javascript
editor_options:
  markdown:
    wrap: sentence
    canonical: true

