on:
  workflow_dispatch:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: quarto publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install system dependencies 
        run: sudo apt-get update && sudo apt-get install -y pandoc libharfbuzz-dev libfreetype6-dev libfribidi-dev libglpk40

      - name: Install Google Fonts
        run: |
          sudo apt-get install -y fonts-open-sans

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
          output_dir: ./_book

      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./_book
          publish_branch: gh-pages


